export const projects = [
  {
    name: "Filmes Populares",
    description:
      "Aplicação WEB para consulta de filmes e criação de lista de favoritos.",
    url: "../portfolio/assets/projectscovers/filmes-cover.webp",
    technologies: ["HTML5", "CSS3", "JavaScript", "Fetch", "TMDB API"],
    github: "https://github.com/filipegallodev/popular-movies",
    test: "https://popular-movies-filipegallodev.vercel.app/",
  },
  {
    name: "Animais Fantásticos",
    description: "Projeto desenvolvido no curso de JavaScript da Origamid.",
    url: "../portfolio/assets/projectscovers/animais-fantasticos-cover.webp",
    technologies: ["HTML5", "CSS3", "JavaScript", "ESLint", "Babel", "Webpack", "Fetch"],
    github: "https://github.com/filipegallodev/javascript-origamid/tree/main/projeto-final/animais-fantasticos",
    test: "https://animais-fantasticos-origamid-fg.vercel.app/",
  },
  {
    name: "Decodificador",
    description: "Aplicação WEB para criptografar e descriptografar textos.",
    url: "../portfolio/assets/projectscovers/decodificador-cover.webp",
    technologies: ["HTML5", "CSS3", "JavaScript", "RegExp"],
    github: "https://github.com/filipegallodev/alura-challenge-criptografia",
    test: "https://filipegallodev.github.io/alura-challenge-criptografia/",
  },
  {
    name: "App de Lista de Notas",
    description: "Aplicação WEB para escrever e salvar notas.",
    url: "../portfolio/assets/projectscovers/noteapp-cover.webp",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    github: "https://github.com/filipegallodev/note-list",
    test: "https://filipegallodev.github.io/note-list/",
  },
  {
    name: "Encurtador de Links",
    description: "Aplicação WEB para encurtar links muito grandes.",
    url: "../portfolio/assets/projectscovers/encurtador-cover.webp",
    technologies: ["HTML5", "CSS3", "JavaScript", "Fetch"],
    github: "https://github.com/filipegallodev/url-shortner",
    test: "https://encurtador-de-links-fg.vercel.app/",
  },
  {
    name: "Optimus Tech - Vagas",
    description: "Página estática de vagas de uma empresa fictícia.",
    url: "../portfolio/assets/projectscovers/optimustech-cover.webp",
    technologies: ["HTML5", "CSS3"],
    github: "https://github.com/filipegallodev/optimus-tech-vagas",
    test: "https://filipegallodev.github.io/optimus-tech-vagas/",
  },
];
